unix format and assemble changes

diff --git a/sti/bin/assemble b/sti/bin/assemble
--- a/sti/bin/assemble
+++ b/sti/bin/assemble
@@ -5,6 +5,10 @@ HOME=/opt/app-root/src
 
 echo "** Customized s2i for OASP4J applications"
 
+ARTIFACT_DIR=${ARTIFACT_DIR:-server/target}
+APP_SUFFIX=${APP_SUFFIX:--bootified}
+APP_EXTENSION=${APP_EXTENSION:-jar}
+
 # we will move any code provided by s2i to here
 LOCAL_SOURCE_DIR=${HOME}/source
 mkdir -p $LOCAL_SOURCE_DIR
@@ -38,92 +42,40 @@ configure_mirrors
 
 manage_incremental_build
 
-# If a pom.xml is present, this is a normal build scenario
-# so run maven.
-if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
-  # the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
-  # artifacts (*.war, *.jar)
-  ARTIFACT_DIR=${ARTIFACT_DIR:-target}
+# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
+# artifacts (*.war, *.jar)
+ARTIFACT_DIR=${ARTIFACT_DIR:-target}
 
-  pushd $LOCAL_SOURCE_DIR &> /dev/null
+pushd $LOCAL_SOURCE_DIR &> /dev/null
 
-  MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga install}
+MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga install}
 
-  # Always force IPv4 (CLOUD-188)
-  # Append user-supplied arguments (CLOUD-412)
-  MAVEN_ARGS="$MAVEN_ARGS -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"
+# Always force IPv4 (CLOUD-188)
+# Append user-supplied arguments (CLOUD-412)
+MAVEN_ARGS="$MAVEN_ARGS -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"
 
-  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
+echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
-  echo "Using $(mvn --version)"
+echo "Using $(mvn --version)"
 
-  # Execute the actual build
-  mvn $MAVEN_ARGS
+# Execute the actual build
+mvn $MAVEN_ARGS
 
-  ERR=$?
-  if [ $ERR -ne 0 ]; then
-    echo "Aborting due to error code $ERR from Maven build"
-    exit $ERR
-  fi
-
-  # Copy built artifacts (if any!) from the target/ directory
-  # (or $ARTIFACT_DIR if specified)
-  # to the $DEPLOY_DIR directory for later deployment
-  copy_artifacts "$ARTIFACT_DIR" jar
-
-  # optionally clear the local maven repository after the build
-  clear_maven_repository
-
-  popd &> /dev/null
-elif [ -f "$LOCAL_SOURCE_DIR/build.gradle" ]; then
-  # the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
-  # artifacts (*.war, *.jar)
-  ARTIFACT_DIR=${ARTIFACT_DIR:-build/libs}
-
-  echo "Building with gradle. $LOCAL_SOURCE_DIR/build.gradle found."
-
-  pushd $LOCAL_SOURCE_DIR &> /dev/null
-
-  if [ -z "$BUILDER_ARGS" ]; then
-    export BUILDER_ARGS="build -x test"
-    # TODO: Specify setting file with -c sss
-  fi
-
-  echo "Found gradle.build ... attempting to build with 'gradle -s ${BUILDER_ARGS}'"
-
-  echo "Gradle version:"
-  gradle --version
-
-  # Execute the actual build
-  gradle -s $BUILDER_ARGS
-
-  ERR=$?
-  if [ $ERR -ne 0 ]; then
-    echo "Aborting due to error code $ERR from Gradle build"
-    exit $ERR
-  fi
-
-  # Copy built artifacts (if any!) from the target/ directory
-  # (or $ARTIFACT_DIR if specified)
-  # to the $DEPLOY_DIR directory for later deployment
-  copy_artifacts "$ARTIFACT_DIR" jar
-
-
-  # clean up after maven
-  gradle clean
-#  if [ -d "$HOME/.m2/repository" ]; then
-#    rm -r "$HOME/.m2/repository"
-#  fi
-
-  popd &> /dev/null
-else
-  # For binary builds
-  # the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
-  # artifacts (*.war, *.jar)
-  ARTIFACT_DIR=${ARTIFACT_DIR:-.}
-
-  copy_artifacts "$ARTIFACT_DIR" jar
+ERR=$?
+if [ $ERR -ne 0 ]; then
+echo "Aborting due to error code $ERR from Maven build"
+exit $ERR
 fi
+
+# Copy built artifacts (if any!) from the target/ directory
+# (or $ARTIFACT_DIR if specified)
+# to the $DEPLOY_DIR directory for later deployment
+copy_artifacts "$ARTIFACT_DIR" "$APP_EXTENSION"
+
+# optionally clear the local maven repository after the build
+clear_maven_repository
+
+popd &> /dev/null
 
 echo "listing contens for debugging build image"
 echo "ls -l ${LOCAL_SOURCE_DIR}"
@@ -141,13 +93,26 @@ ls -l ${ARTIFACT_DIR}
 echo "ls ${LOCAL_SOURCE_DIR}/${ARTIFACT_APP}"
 ls -h ${LOCAL_SOURCE_DIR}/${ARTIFACT_APP}
 
-if [ $(ls ${LOCAL_SOURCE_DIR}/${ARTIFACT_APP} | wc -l) -eq 1 ]; then
-  echo "[INFO] Copying ${LOCAL_SOURCE_DIR}/${ARTIFACT_APP} into ${DEPLOY_DIR}/app.jar"
-  cp ${LOCAL_SOURCE_DIR}/${ARTIFACT_APP} ${DEPLOY_DIR}/app.jar
-  [ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
-  echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
+if [ -n "$DEBUG_BUILD" ]; then
+	 echo "DEBUG_BUILD: $DEBUG_BUILD"
+	 echo "HOME: $HOME"
+	 echo "LOCAL_SOURCE_DIR: $LOCAL_SOURCE_DIR"
+	 echo "ARTIFACT_DIR: $ARTIFACT_DIR"
+	 echo "ARTIFACT_APP: $ARTIFACT_APP"
+	 echo "APP_EXTENSION: $APP_EXTENSION"
+	 echo "DEPLOY_DIR: $DEPLOY_DIR"
+	  echo "Output of the build process"
+	  find .
+fi
+
+
+if [ $(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.${APP_EXTENSION} | wc -l) -eq 1 ]; then
+  echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.${APP_EXTENSION} into ${DEPLOY_DIR}/app.$APP_EXTENSION"
+  cp ${DEPLOY_DIR}/*${APP_SUFFIX}.${APP_EXTENSION} ${DEPLOY_DIR}/app.${APP_EXTENSION}
+  [ ! -f ${DEPLOY_DIR}/app.${APP_EXTENSION} ] && echo "Application could not be properly built." && exit 1
+  echo "[INFO] Application $APP_EXTENSION file is located in ${DEPLOY_DIR}/app.${APP_EXTENSION}"
 else
-  echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}"
+  echo "[ERROR] No app.$APP_EXTENSION file located in ${DEPLOY_DIR}"
   exit 1
 fi
 
